services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  flightclientapp:
    container_name: ui
    image: ${DOCKER_REGISTRY-}flightclientapp
    build:
      context: FlightClientApp
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:8080"
      Api__BaseUrl: "http://api:8080"
    depends_on:
      - flightstorageservice
    ports:
      - "8082:8080"

  flightstorageservice:
    container_name: api
    image: ${DOCKER_REGISTRY-}flightstorageservice
    build:
      context: FlightStorageService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - sqlserver
    ports:
      - "8081:8080"

volumes:
  mssql_data:
